theme: cayman
title: "Portafolio Digital - Teoría de la Programación"
description: "Unidad 1 - Algoritmos y Estructuras Secuenciales"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# If deploying as a project page, uncomment and set baseurl:
# baseurl: "/Teoria-de-la-Programacion1"
# url: "https://yimmyonner.github.io"
